# Generated by Django 4.0.4 on 2022-06-23 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_alter_event_date_result_event_voting'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_operation',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='Mmeber_Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(default='', max_length=255)),
                ('end_time', models.CharField(default='', max_length=255)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.member')),
            ],
        ),
    ]
