# Generated by Django 4.0.5 on 2022-07-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_rename_mmeber_calendar_membercalendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_voting',
            name='reason',
            field=models.TextField(default=''),
        ),
    ]
